<h1>Chapter 02. An Array  Sequences.</h1>

<h2>List Comprehensions and Generator Expressions</h2>

Build a list of Unicode codepoints from a string

In [1]:
symbols = '$¢£¥€¤'
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

Build a list of Unicodse codepoints from a string using list comprehension

In [2]:
symbols = '$¢£¥€¤'
codes = [
    ord(symbol) for symbol in symbols
]

codes

[36, 162, 163, 165, 8364, 164]

The same list built by a listcomp and map/filter composition

In [3]:
symbols = '$¢£¥€¤'
beyond_ascii = [
    ord(s) for s in symbols if ord(s) > 127
]

beyond_ascii

[162, 163, 165, 8364, 164]

In [4]:
symbols = '$¢£¥€¤'
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))

beyond_ascii

[162, 163, 165, 8364, 164]

Cartesian product using a list comprehension

In [5]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

tshirts = [
    (color, size) for color in colors
    for size in sizes
]

tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [6]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [7]:
tshirts = [
    (color, size) for size in sizes
    for color in colors
]

tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

Initializing a tuple and an array from a generator expression

In [8]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [9]:
import array


array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

Cartesian product in a generator expression

In [10]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in (f'{c} {s}' for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


<h2>Tuples are not only Immutable Lists</h2>

Tuples used as records

In [11]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [
    ('USA', '31195855'),
    ('BRA', 'CE342567'),
    ('ESP', 'XDA205856')
]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [12]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


Tuples as Immutable Lists

In [13]:
a = (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])
a == b

True

In [14]:
b[-1].append(99)
a == b

False

In [15]:
b

(10, 'alpha', [1, 2, 99])

In [16]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

tf = (10, 'alpha', (1, 2))  # contains no mutable items
tm = (10, 'alpha', [1, 2])  # contains a mutable items (list)
fixed(tf)

True

In [17]:
fixed(tm)

False

<h2>Unpacking Sequences and Iterables</h2>

In [18]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates  # unpacking

In [19]:
latitude

33.9425

In [20]:
longitude

-118.408056

In [21]:
divmod(20, 8)

(2, 4)

In [22]:
t = (20, 8)
divmod(*t)

(2, 4)

In [23]:
quotient, reminder = divmod(*t)
quotient, reminder

(2, 4)

<h3>Using <code>*</code> to grab excess items</h3>

In [24]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [25]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [26]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [27]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [28]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

<h3>Unpacking with <code>*</code> in function calls and sequence literals</h3>

In [29]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

fun(*[1, 2], 3, *range(4, 7))

(1, 2, 3, 4, (5, 6))

In [30]:
*range(4), 4

(0, 1, 2, 3, 4)

In [31]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [32]:
{*range(4), 4, *(5, 6, 7)}

{0, 1, 2, 3, 4, 5, 6, 7}

<h3>Unpacking nested objects</h3>

Unpacking nested tuples to access the longitude

In [33]:
METRO_AREAS = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]


def main():
    print(f"{'':15} | {'latitude':>9} | {'longitude':>9}")
    
    for name, _, _, (lat, lon) in METRO_AREAS:
        if lon <= 0:  # only megacities in the Western hemisphere
            print(f"{name:15} | {lat:9.4f} | {lon:9.4f}")


if __name__ == '__main__':
    main()   

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


<h2>Pattern matching with Sequences</h2>

Method from an imaginary Robot class

In [34]:
# class Robot:

#     def handle_command(self, message):
#         match message:
#             case ['BEEPER', frequency, times]:
#                 self.beep(times, frequency)
#             case ['NECK', angle]:
#                 self.rotate_neck(angle)
#             case ['LED', ident, intensity]:
#                 self.leds[ident].set_brightness(ident, intensity)
#             case ['LED', ident, red, green, blue]:
#                 self.leds[ident].set_color(ident, red, green, blue)
#             case _:
#                 raise InvalidCommand(message)

Destructuring nested tuples (requires Python >= 3.10)

In [35]:
METRO_AREAS = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]


# using match/case
def main():
    print(f"{'':15} | {'latitude':>9} | {'longitude':>9}")

    for record in METRO_AREAS:
        match record:
            case [name, _, _, (lat, lon)] if lon <= 0:
                print(f"{name:15} | {lat:9.4f} | {lon:9.4f}")


if __name__ == '__main__':
    main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


<h3>Pattern Matching Sequences in an Interpreter</h3>

Pattern matching with match/case

In [36]:
class Command:
    def __init__(self, name, *args):
        self.name = name
        self.args = args

def interpret_command(commands):
    for cmd in commands:
        match cmd:
            case Command(name='print', args=args) if all(isinstance(arg, str) for arg in args):
                print(' '.join(args) + '!')
            case Command(name='sum', args=args) if all(isinstance(arg, int) for arg in args):
                print(f"Args sum: {sum(args)}")
            case Command(name='exit'):
                print("Exiting the interpreter...")
            case _:
                print("Invalid or unsupported command")

# Sample command sequences to interpret
commands = [
    Command('print', 'Hello', 'World'),
    Command('sum', 10, 20, 30),
    Command('exit'),
    Command('unknown')
]

# Interpret each command
interpret_command(commands)

Hello World!
Args sum: 60
Exiting the interpreter...
Invalid or unsupported command


<h2>Slicing</h2>

<h3>Why Slices and Range exclude the Last Item</h3>

Because it's indexed from 0, you'll get the length, but not the last element.

In [37]:
my_list = list(range(5))  # length 5
my_list

[0, 1, 2, 3, 4]

In [38]:
my_list[:5]  # length 5

[0, 1, 2, 3, 4]

<h3>Slice Objects</h3>

In [39]:
s = 'bicycle'
s[::3]

'bye'

In [40]:
s[::-1]

'elcycib'

In [41]:
s[::-2]

'eccb'

To calculate the expression `seq[start:stop:slice]`, Python calls method `seq.__getitem__(slice(start, stop, step))`

Line items from a flat-line invoice

In [42]:
INVOICE = """
0....5..................................40........52...55........
1909 Pimoroni PiBrella                      $17.50    3    $52.50
1489 6mm Tactile Switch x20                  $4.95    2    $9.90
1510 Panavise Jr. - PV-201                  $28.00    1    $28.00
1601 PiTFT Mini Kit 320x240                 $34.95    1    $34.95
"""

SKU = slice(0, 6)
DESCRIPTION = slice(5, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = INVOICE.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   Pimoroni PiBrella                  
     $4.95   6mm Tactile Switch x20             
    $28.00   Panavise Jr. - PV-201              
    $34.95   PiTFT Mini Kit 320x240             
 


<h3>Assigning to Slices</h3>

In [43]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [45]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [46]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [47]:
try:
    l[2:5] = 100
except TypeError as e:
    print(e.__repr__())

TypeError('can only assign an iterable')


In [48]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

<h3>Using <code>+</code> and <code>*</code> with Sequences</h3>

In [49]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [50]:
l1 = [4, 5, 6]
l + l1

[1, 2, 3, 4, 5, 6]

In [51]:
5 * 'abc_'

'abc_abc_abc_abc_abc_'

<h3>Building a Lists of Lists</h3>

A list with three lists of length 3 can represent a tic-tac-toe board 

In [52]:
board = [['_'] * 3 for _ in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [53]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

A list with three references to the same list is useless

In [54]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [55]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

`weird_board` works like the folowing code

In [56]:
row = ['_'] * 3
weird_board = []
for i in range(3):
    weird_board.append(row)  # same object is added three times

`board` works like the following code

In [57]:
board = []
for i in range(3):
    row = ['_'] * 3  # each iteration builds a new row
    board.append(row)

<h2>Augmented Assignment with Sequences</h2>

In [58]:
l = [1, 2, 3]
id(l)  # get list id

4434766464

In [59]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [60]:
id(l)  # get list id again

4434766464

After multiplication, the list is the same.

In [61]:
t = (1, 2, 3)
id(t)  # get tuple id

4434693568

In [62]:
t *= 2
t

(1, 2, 3, 1, 2, 3)

In [63]:
id(t)  # get tuple id again

4433696352

After multiplication, a new tuple is created.

<h3>A <code>+=</code> Assigment Puzzler</h3>

A riddle

In [64]:
t = (1, 2, [30, 40])
try:
    t[2] += [50, 60]
except TypeError as e:
    print(e.__repr__())

TypeError("'tuple' object does not support item assignment")


The unexpected result: item `t` is changed and an exception is raised

In [65]:
t

(1, 2, [30, 40, 50, 60])

Bytecode for the expression `s[a] += b`

In [66]:
import dis


dis.dis('s[a] += b')

  0           0 RESUME                   0

  1           2 LOAD_NAME                0 (s)
              4 LOAD_NAME                1 (a)
              6 COPY                     2
              8 COPY                     2
             10 BINARY_SUBSCR
             14 LOAD_NAME                2 (b)
             16 BINARY_OP               13 (+=)
             20 SWAP                     3
             22 SWAP                     2
             24 STORE_SUBSCR
             28 RETURN_CONST             0 (None)


<h2>The Method <code>list.sort()</code> and <code>sorted()</code> Built-in Function</h2>

`sort()` is a method that sorts the elements of a list in place (modifies the original list).
`sorted()` is a built-in function that returns a new sorted list from the elements of any iterable. 

In [67]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [68]:
fruits  # original list is not changed

['grape', 'raspberry', 'apple', 'banana']

In [69]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [70]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [71]:
fruits  # original list still unchanged

['grape', 'raspberry', 'apple', 'banana']

In [72]:
fruits.sort()
fruits  # original list is changed

['apple', 'banana', 'grape', 'raspberry']

<h2>When a List is not the Answer</h2>

<h3>Arrays</h3>

Creating, saving and loading a large array of floats

In [73]:
from array import array
from random import random, seed


seed(10)  # use to make the output consistent

# Generates an array of double-precision floats using 'd' type
floats = array('d', (random() for _ in range(10 ** 7)))
floats[-1]

0.8190492979077034

In [74]:
with open('floats.bin', 'wb') as fp:
    floats.tofile(fp)

In [75]:
# Create an empty array of double-precision floating-point numbers
floats2 = array('d')

with open('floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10 ** 7)   # read 10 million numbers from a binary file

floats2[-1]

0.8190492979077034

In [76]:
floats2 == floats

True

<h3>Memory Views</h3>

`memoryview` is a Python built-in class that offers a non-copying, efficient view into the memory of objects supporting the buffer protocol. It allows direct access to an object's internal data without creating duplicates, enabling efficient manipulation of large data objects like bytes or arrays.

Hadling 6 bytes memory of as 1x6, 2x3, and 3x2 views

In [77]:
from array import array


# Create an array with a 6-byte ('B' type code)
octets = array('B', range(6))

m1 = memoryview(octets)
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [78]:
# Create a new memoryview using the previous one, but with 2 rows and 3 columns
m2 = m1.cast('B', [2, 3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [79]:
# Create a new memoryview using the previous one, but with 3 rows and 2 columns
m3 = m1.cast('B', [3, 2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [80]:
# Reassign byte in row 1 column 1
m2[1, 1] = 22
m3[1, 1] = 33

octets

array('B', [0, 1, 2, 33, 22, 5])

Changing the value of a 16-bit integer array item by poking one of its bytes

In [81]:
# Generate an array of signed short integers using 'h' type
numbers = array('h', [-2, -1, 0, 1, 2])

memv = memoryview(numbers)
memv.tolist()

[-2, -1, 0, 1, 2]

In [82]:
len(memv)

5

In [83]:
memv[0]

-2

In [84]:
# Create an object by converting elements to type 'B' code
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [85]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

<h3>NumPy</h3>

NumPy is a powerful Python library for numerical computations, specifically designed to handle arrays and matrices.

Basic operations with rows and columns in a `numpy.ndarray`

In [86]:
import numpy as np


a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
type(a)

numpy.ndarray

In [88]:
# Print the array dimensions
a.shape

(12,)

In [89]:
# Change arrays form
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a[2]  # get row with index 2

array([ 8,  9, 10, 11])

In [91]:
a[2][1]  # get item from row 2, column 1

9

In [92]:
a[:, 1]  # get column with index 1

array([1, 5, 9])

In [93]:
# Create a new array by transposing the original array (rearranging rows and columns)
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Loading, saving, and vectorized operations

In [94]:
with open('floats-1M-lines.txt', 'wt') as fp:
    for _ in range(1000000):
        fp.write(f"{random()}\n")

In [95]:
floats = np.loadtxt('floats-1M-lines.txt')

In [96]:
floats[-3:]

array([0.06078257, 0.61741189, 0.84349987])

In [97]:
floats *= 0.5  # multiply each element by 0.5
floats[-3:]

array([0.03039128, 0.30870594, 0.42174994])

In [98]:
from time import perf_counter


t0 = perf_counter()
floats /= 3
print(f"The division process time is {round((perf_counter() - t0), 3)} seconds.")

The division process time is 0.002 seconds.


In [99]:
np.save('floats-1M', floats)

In [100]:
floats2 = np.load('floats-1M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([0.06078257, 0.61741189, 0.84349987])

<h3>Deques and Other Queues</h3>

`collections.deque`: Double-ended queue implementation in Python's collections module for efficient and thread-safe manipulation of items with fast appends and pops on both ends.

Working with deque

In [101]:
from collections import deque


dq = deque(range(10), maxlen=10)  # the optional argument maxlen= specifies the maximum number of elements
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [102]:
dq.rotate(3)  # move 3 elements from one end to other
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [103]:
dq.rotate(-3)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [104]:
dq.appendleft(-1)
dq

deque([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8], maxlen=10)

In [105]:
dq.extend([11, 22, 33])
dq

deque([2, 3, 4, 5, 6, 7, 8, 11, 22, 33], maxlen=10)

In [106]:
dq.extendleft([10, 20, 30])
dq

deque([30, 20, 10, 2, 3, 4, 5, 6, 7, 8], maxlen=10)

<h2>Mixed Lists</h2>

<h3><code>key=</code> is Brilliant</h3>

In [107]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]

try:
    sorted(l)
except TypeError as e:
    print(e.__repr__())

TypeError("'<' not supported between instances of 'str' and 'int'")


`key=int` sorts list numerically treating elements as integers

In [108]:
sorted(l, key=int)

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']

`key=str` sorts list lexicographically considering elements as strings

In [109]:
sorted(l, key=str)

[0, '1', 14, 19, '23', 28, '28', 5, 6, '9']